import { type ChangeEvent, type Dispatch, type FormEvent, type SetStateAction, useEffect, useMemo, useRef, useState } from "react";
import type { AppState, CashDraft, CashSession, Currency, Mode, Reward, Room, StoredVault, Tab, TournamentDraft, Vault } from "./types";
import { bigBlind, cashDraft, decryptState, demoState, deriveKey, emptyState, encryptState, loadVaults, money, num, percent, roomCurrency, roomName, saveVaults, signed, today, tournamentDraft, uid } from "./data";

type Setter = Dispatch<SetStateAction<AppState | null>>;
const roomFilter = (state: AppState, mode: Mode) => state.rooms.filter((r) => r.kind === "room" && (r.mode === mode || r.mode === "both"));

function Metric({ label, value, note, tone = "" }: { label: string; value: string; note: string; tone?: string }) {
  return <article className="metric"><span>{label}</span><strong className={tone}>{value}</strong><small>{note}</small></article>;
}
function Empty({ children }: { children: string }) { return <div className="empty"><b>—</b><span>{children}</span></div>; }

function ProfitChart({ points }: { points: { date: string; value: number }[] }) {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = ref.current; if (!canvas) return;
    const draw = () => {
      const box = canvas.getBoundingClientRect(), dpr = window.devicePixelRatio || 1;
      canvas.width = box.width * dpr; canvas.height = box.height * dpr;
      const c = canvas.getContext("2d"); if (!c) return; c.scale(dpr, dpr); c.clearRect(0, 0, box.width, box.height);
      if (!points.length) return; const values = points.map((p) => p.value), min = Math.min(0, ...values), max = Math.max(1, ...values), span = max - min || 1;
      const x = (i: number) => 18 + i / Math.max(1, points.length - 1) * (box.width - 36), y = (v: number) => 18 + (max - v) / span * (box.height - 46);
      c.strokeStyle = "#303030"; c.beginPath(); c.moveTo(18, y(0)); c.lineTo(box.width - 18, y(0)); c.stroke();
      const g = c.createLinearGradient(0, 18, 0, box.height - 28); g.addColorStop(0, "rgba(126,231,135,.24)"); g.addColorStop(1, "rgba(126,231,135,0)");
      c.beginPath(); points.forEach((p, i) => i ? c.lineTo(x(i), y(p.value)) : c.moveTo(x(i), y(p.value))); c.lineTo(x(points.length - 1), box.height - 28); c.lineTo(x(0), box.height - 28); c.closePath(); c.fillStyle = g; c.fill();
      c.beginPath(); points.forEach((p, i) => i ? c.lineTo(x(i), y(p.value)) : c.moveTo(x(i), y(p.value))); c.strokeStyle = "#7ee787"; c.lineWidth = 2.5; c.lineJoin = "round"; c.stroke();
      points.forEach((p, i) => { c.beginPath(); c.arc(x(i), y(p.value), 3, 0, Math.PI * 2); c.fillStyle = "#111"; c.fill(); c.strokeStyle = "#7ee787"; c.stroke(); });
      c.fillStyle = "#777"; c.font = "10px Inter"; c.fillText(points[0].date.slice(5), 18, box.height - 7); const end = points.at(-1)!.date.slice(5); c.fillText(end, box.width - 18 - c.measureText(end).width, box.height - 7);
    };
    draw(); const observer = new ResizeObserver(draw); observer.observe(canvas); return () => observer.disconnect();
  }, [points]);
  return <canvas ref={ref} className="chart" aria-label="Cumulative USD profit graph" />;
}

function Gate({ vaults, setVaults, enter }: { vaults: StoredVault[]; setVaults: Dispatch<SetStateAction<StoredVault[]>>; enter: (state: AppState, key?: CryptoKey, salt?: Uint8Array, demo?: boolean, vaultId?: string) => void }) {
  const [error, setError] = useState(""), [creating, setCreating] = useState(vaults.length === 0), [selectedId, setSelectedId] = useState(vaults[0]?.id || "");
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setError(""); const form = new FormData(event.currentTarget), pin = String(form.get("pin") || "");
    try {
      if (!creating) {
        const stored = vaults.find((vault) => vault.id === selectedId); if (!stored) throw new Error("missing");
        const opened = await decryptState(stored.vault, pin); enter(opened.state, opened.key, opened.salt, false, stored.id);
      } else {
        if (pin.length < 4) throw new Error("short");
        const salt = crypto.getRandomValues(new Uint8Array(16)), key = await deriveKey(pin, salt), state = emptyState(String(form.get("name") || "Player").trim() || "Player"), id = uid();
        const next = [...vaults, { id, name: state.profileName, vault: await encryptState(state, key, salt) }]; saveVaults(next); setVaults(next); enter(state, key, salt, false, id);
      }
    } catch (reason) { setError(reason instanceof Error && reason.message === "short" ? "Use at least 4 characters for your PIN." : "That PIN does not unlock this vault."); }
  };
  return <main className="gate"><section><div className="logo">GT</div><p className="eyebrow">ONLINE POKER JOURNAL</p><h1>Own your grind.</h1><p className="lead">Cash and tournament performance without the spreadsheet. Your records are encrypted and stay on this device.</p>
    <form onSubmit={submit}>{creating ? <label>Player name<input name="name" autoFocus placeholder="Your screen name" /></label> : <label>Account<select value={selectedId} onChange={(event)=>setSelectedId(event.target.value)}>{vaults.map((vault)=><option value={vault.id} key={vault.id}>{vault.name}</option>)}</select></label>}<label>{creating ? "Create private PIN" : "Private PIN"}<input name="pin" type="password" autoFocus={!creating} placeholder={creating ? "4+ characters" : "Enter your PIN"} /></label>{error && <p className="error">{error}</p>}<button className="primary">{creating ? "Create private vault" : "Unlock GrindTrack"}</button></form>
    {vaults.length>0&&<button className="secondary account-switch" onClick={()=>{setCreating((value)=>!value);setError("")}}>{creating?"Back to my accounts":"+ Create another account"}</button>}
    <button className="link" onClick={() => enter(demoState(), undefined, undefined, true)}>Explore with demo data →</button><div className="privacy"><i>●</i><span><b>Device-only by design</b><small>Friends use the same link, but get a separate vault in their own browser.</small></span></div>
  </section></main>;
}

function Dashboard({ state, mode }: { state: AppState; mode: Mode }) {
  const stats = useMemo(() => {
    if (mode === "tournament") {
      const entries = state.tournamentDays.flatMap((d) => d.entries).filter((e) => roomCurrency(state.rooms, e.roomId) === "USD");
      const buy = entries.reduce((s, e) => s + e.buyIns, 0), cash = entries.reduce((s, e) => s + e.cashes, 0), volume = entries.reduce((s, e) => s + e.tournaments, 0);
      const rewards = state.rewards.filter((r) => r.mode === mode && roomCurrency(state.rooms, r.roomId) === "USD").reduce((s, r) => s + r.amount, 0);
      return { pure: cash - buy, rewards, total: cash - buy + rewards, volume, hours: state.tournamentDays.reduce((s, d) => s + d.duration, 0), one: volume ? buy / volume : 0, two: buy ? (cash - buy) / buy * 100 : 0, rake: 0 };
    }
    const sessions = state.cashSessions.filter((s) => roomCurrency(state.rooms, s.roomId) === "USD");
    const pure = sessions.reduce((s, x) => s + x.tableResult, 0), builtIn = sessions.reduce((s, x) => s + x.lbReward + x.rakeback + x.bonuses, 0), external = state.rewards.filter((r) => r.mode === mode && roomCurrency(state.rooms, r.roomId) === "USD").reduce((s, r) => s + r.amount, 0);
    const volume = sessions.reduce((s, x) => s + x.hands, 0), hours = sessions.reduce((s, x) => s + x.hours, 0), rake = sessions.reduce((s, x) => s + x.rake, 0), bbWon = sessions.reduce((s, x) => s + x.tableResult / (bigBlind(x.stake) || 1), 0);
    return { pure, rewards: builtIn + external, total: pure + builtIn + external, volume, hours, one: hours ? (pure + builtIn + external) / hours : 0, two: volume ? bbWon / volume * 100 : 0, rake };
  }, [state, mode]);
  const points = useMemo(() => { const days = new Map<string, number>(); if (mode === "tournament") state.tournamentDays.forEach((d) => d.entries.forEach((e) => roomCurrency(state.rooms, e.roomId) === "USD" && days.set(d.date, (days.get(d.date) || 0) + e.cashes - e.buyIns))); else state.cashSessions.forEach((s) => roomCurrency(state.rooms, s.roomId) === "USD" && days.set(s.date, (days.get(s.date) || 0) + s.tableResult + s.lbReward + s.rakeback + s.bonuses)); state.rewards.filter((r) => r.mode === mode && roomCurrency(state.rooms, r.roomId) === "USD").forEach((r) => days.set(r.date, (days.get(r.date) || 0) + r.amount)); let running = 0; return [...days].sort(([a], [b]) => a.localeCompare(b)).map(([date, value]) => ({ date, value: running += value })); }, [state, mode]);
  const recent = mode === "tournament" ? [...state.tournamentDays].sort((a,b) => b.date.localeCompare(a.date)).slice(0,5).map((d) => ({ id:d.id,date:d.date,name:`${d.entries.length} rooms`,detail:`${d.entries.reduce((s,e)=>s+e.tournaments,0)} MTTs`,result:d.entries.reduce((s,e)=>s+e.cashes-e.buyIns,0),currency:"USD" as Currency })) : [...state.cashSessions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map((s)=>({id:s.id,date:s.date,name:roomName(state.rooms,s.roomId),detail:`${s.stake} · ${s.hands.toLocaleString()} hands`,result:s.tableResult+s.lbReward+s.rakeback+s.bonuses,currency:roomCurrency(state.rooms,s.roomId)}));
  return <div className="stack"><section className="hero"><div><p className="eyebrow">OVERALL RESULT · USD</p><strong className={stats.total >= 0 ? "pos" : "neg"}>{signed(stats.total)}</strong><small>{stats.volume.toLocaleString()} {mode === "tournament" ? "tournaments" : "hands"} · {stats.hours.toFixed(1)} hours</small></div><aside><span>Pure profit<b>{signed(stats.pure)}</b></span><span>RB + bonuses<b>{signed(stats.rewards)}</b></span></aside></section>
    <section className="metrics">{mode === "tournament" ? <><Metric label="ABI" value={money(stats.one)} note="Average buy-in"/><Metric label="ROI" value={percent(stats.two)} note="Before rakeback" tone={stats.two >= 0 ? "pos" : "neg"}/><Metric label="$/MTT" value={money(stats.volume ? stats.pure / stats.volume : 0)} note="Pure profit per entry"/><Metric label="Rewards share" value={percent(stats.total ? stats.rewards / Math.abs(stats.total) * 100 : 0)} note="Of overall result"/></> : <><Metric label="Win rate" value={`${stats.two.toFixed(2)} bb/100`} note="Table result only" tone={stats.two >= 0 ? "pos" : "neg"}/><Metric label="$/hour" value={money(stats.one)} note="Including rewards" tone={stats.one >= 0 ? "pos" : "neg"}/><Metric label="Total rake" value={money(stats.rake)} note="Tracked sessions"/><Metric label="Actual RB" value={percent(stats.rake ? stats.rewards / stats.rake * 100 : 0)} note="Rewards ÷ rake"/></>}</section>
    <section className="panel"><header><div><p className="eyebrow">PERFORMANCE</p><h2>Overall graph</h2></div><small className="legend"><i/> Cumulative USD</small></header>{points.length ? <ProfitChart points={points}/> : <Empty>Add your first result to draw the graph.</Empty>}</section>
    <section className="panel"><header><div><p className="eyebrow">LATEST</p><h2>Recent grind</h2></div></header>{recent.length ? <div className="list">{recent.map((x)=><div className="row" key={x.id}><time>{x.date}</time><b>{x.name}</b><span>{x.detail}</span><strong className={x.result>=0?"pos":"neg"}>{signed(x.result,x.currency)}</strong></div>)}</div>:<Empty>No sessions yet. Your latest results will appear here.</Empty>}</section>
  </div>;
}

function BalanceInput({ value, currency, onCommit }: { value: number; currency: Currency; onCommit: (value: number) => void }) {
  const [text, setText] = useState(String(value));
  useEffect(() => setText(String(value)), [value]);
  return <div className="money-field"><i>{currency === "USD" ? "$" : "€"}</i><input aria-label="Current balance" type="number" step=".01" value={text} onChange={(event)=>{const next=event.target.value;setText(next);if(next!=="")onCommit(Number(next))}} onBlur={()=>{if(text===""){setText("0");onCommit(0)}}}/></div>;
}

function Balances({ state, setState, mode }: { state: AppState; setState: Setter; mode: Mode }) {
  const rooms = state.rooms.filter((r) => r.mode === mode || r.mode === "both" || r.kind === "wallet");
  const usd = rooms.filter((r)=>r.currency==="USD").reduce((sum,room)=>sum+room.currentBalance,0), eur = rooms.filter((r)=>r.currency==="EUR").reduce((sum,room)=>sum+room.currentBalance,0);
  const resultToday = (id:string) => mode === "tournament" ? state.tournamentDays.filter((d)=>d.date===today).flatMap((d)=>d.entries).filter((e)=>e.roomId===id).reduce((s,e)=>s+e.cashes-e.buyIns,0) : state.cashSessions.filter((x)=>x.date===today&&x.roomId===id).reduce((s,x)=>s+x.tableResult+x.lbReward+x.rakeback+x.bonuses,0);
  const add = (event:FormEvent<HTMLFormElement>) => { event.preventDefault(); const f=new FormData(event.currentTarget), balance=num(f.get("balance")); setState((s)=>s&&({...s,rooms:[...s.rooms,{id:uid(),name:String(f.get("name")),kind:String(f.get("kind")) as Room["kind"],mode:String(f.get("mode")) as Room["mode"],currency:String(f.get("currency")) as Currency,startingBalance:balance,currentBalance:balance}]})); event.currentTarget.reset(); };
  return <div className="stack"><section className="bankroll bankroll-total"><div><span>USD bankroll</span><b>{money(usd)}</b></div><div><span>EUR bankroll</span><b>{money(eur,"EUR")}</b></div><div><span>Total bankroll</span><b>{(usd+eur).toLocaleString("en-US",{maximumFractionDigits:2})}</b><small>USD + EUR · no conversion</small></div><p>Saving a daily result automatically updates that room’s current balance. You can still reconcile it manually.</p></section><section className="room-grid">{rooms.map((r)=><article className="room" key={r.id}><header><i>{r.name.slice(0,2).toUpperCase()}</i><span><b>{r.name}</b><small>{r.kind} · {r.currency}</small></span><strong className={resultToday(r.id)>=0?"pos":"neg"}>{signed(resultToday(r.id),r.currency)}</strong></header><label>Current balance<BalanceInput value={r.currentBalance} currency={r.currency} onCommit={(value)=>setState((s)=>s&&({...s,rooms:s.rooms.map((x)=>x.id===r.id?{...x,currentBalance:value}:x)}))}/></label><footer><span>Starting<b>{money(r.startingBalance,r.currency)}</b></span><span>Change<b className={r.currentBalance-r.startingBalance>=0?"pos":"neg"}>{signed(r.currentBalance-r.startingBalance,r.currency)}</b></span></footer></article>)}</section><section className="panel"><header><div><p className="eyebrow">BANKROLL</p><h2>Add room or wallet</h2></div></header><form className="inline" onSubmit={add}><label>Name<input name="name" required placeholder="e.g. Nike"/></label><label>Type<select name="kind"><option value="room">Poker room</option><option value="wallet">Wallet</option></select></label><label>Used for<select name="mode" defaultValue={mode}><option value="tournament">MTT</option><option value="cash">Cash</option><option value="both">Both</option></select></label><label>Currency<select name="currency"><option>USD</option><option>EUR</option></select></label><label>Starting balance<input name="balance" type="number" step=".01" placeholder="0"/></label><button className="primary">Add</button></form></section></div>;
}

function TournamentDaily({ state, setState }: { state: AppState; setState: Setter }) {
  const rooms=roomFilter(state,"tournament"), draft=state.drafts.tournament;
  const updateDraft=(update:(draft:TournamentDraft)=>TournamentDraft)=>setState((current)=>current&&({...current,drafts:{...current.drafts,tournament:update(current.drafts.tournament)}}));
  const changeRow=(key:string,field:keyof TournamentDraft["rows"][number],value:string)=>updateDraft((current)=>({...current,rows:current.rows.map((row)=>row.key===key?{...row,[field]:value}:row)}));
  const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const entries=draft.rows.filter((row)=>row.roomId&&(row.tournaments||row.buyIns||row.cashes)).map((row)=>({roomId:row.roomId,tournaments:Number(row.tournaments||0),buyIns:Number(row.buyIns||0),cashes:Number(row.cashes||0)}));if(!entries.length)return;setState((current)=>{if(!current)return current;const roomResults=new Map<string,number>();entries.forEach((entry)=>roomResults.set(entry.roomId,(roomResults.get(entry.roomId)||0)+entry.cashes-entry.buyIns));return {...current,tournamentDays:[...current.tournamentDays,{id:uid(),date:draft.date,duration:Number(draft.duration||0),notes:draft.notes,entries}],rooms:current.rooms.map((room)=>({...room,currentBalance:room.currentBalance+(roomResults.get(room.id)||0)})),drafts:{...current.drafts,tournament:tournamentDraft(rooms[0]?.id||"")}}});};
  const total=draft.rows.reduce((sum,row)=>sum+Number(row.cashes||0)-Number(row.buyIns||0),0),count=draft.rows.reduce((sum,row)=>sum+Number(row.tournaments||0),0),buy=draft.rows.reduce((sum,row)=>sum+Number(row.buyIns||0),0);
  return <div className="stack"><section className="entry-intro"><div><p className="eyebrow">FAST DAILY ENTRY</p><h2>One row per room. Not per tournament.</h2><p>Enter totals after the session. Leave Total cashes blank when you cashed $0; a $50 buy-in will save as −$50 automatically.</p></div><aside><span>Session result</span><b className={total>=0?"pos":"neg"}>{signed(total)}</b><small>{count} MTTs · ABI {money(count?buy/count:0)}</small></aside></section><section className="panel"><form className="entry" onSubmit={save}><div className="form-grid top"><label>Date<input type="date" value={draft.date} onChange={(event)=>updateDraft((current)=>({...current,date:event.target.value}))} required/></label><label>Duration<input type="number" step=".1" placeholder="Hours" value={draft.duration} onChange={(event)=>updateDraft((current)=>({...current,duration:event.target.value}))}/></label><label>Notes<input placeholder="Focus, mistakes, deep runs…" value={draft.notes} onChange={(event)=>updateDraft((current)=>({...current,notes:event.target.value}))}/></label></div><div className="draft-note">Draft saved automatically while you check other tabs.</div><div className="entry-table"><header><span>Room</span><span>Tournaments</span><span>Total buy-ins</span><span>Total cashes</span><span>Result</span><span/></header>{draft.rows.map((row)=><div key={row.key}><select value={row.roomId} onChange={(event)=>changeRow(row.key,"roomId",event.target.value)}>{rooms.map((room)=><option key={room.id} value={room.id}>{room.name} · {room.currency}</option>)}</select><input aria-label="Tournaments" type="number" placeholder="0" value={row.tournaments} onChange={(event)=>changeRow(row.key,"tournaments",event.target.value)}/><input aria-label="Buy-ins" type="number" step=".01" placeholder="0" value={row.buyIns} onChange={(event)=>changeRow(row.key,"buyIns",event.target.value)}/><input aria-label="Cashes" type="number" step=".01" placeholder="0 · leave blank" value={row.cashes} onChange={(event)=>changeRow(row.key,"cashes",event.target.value)}/><b className={Number(row.cashes||0)-Number(row.buyIns||0)>=0?"pos":"neg"}>{signed(Number(row.cashes||0)-Number(row.buyIns||0),roomCurrency(state.rooms,row.roomId))}</b><button type="button" aria-label="Remove room row" className="remove" onClick={()=>updateDraft((current)=>({...current,rows:current.rows.filter((item)=>item.key!==row.key)}))}>×</button></div>)}</div><footer><button type="button" className="secondary" onClick={()=>updateDraft((current)=>({...current,rows:[...current.rows,{key:uid(),roomId:rooms[0]?.id||"",tournaments:"",buyIns:"",cashes:""}]}))}>+ Add room</button><button className="primary">Save daily result</button></footer></form></section><History state={state} setState={setState} mode="tournament"/></div>;
}

function CashDaily({ state, setState }: { state: AppState; setState: Setter }) {
  const rooms=roomFilter(state,"cash"),draft=state.drafts.cash;
  const change=(field:keyof CashDraft,value:string)=>setState((current)=>current&&({...current,drafts:{...current.drafts,cash:{...current.drafts.cash,[field]:value}}}));
  const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const session:CashSession={id:uid(),date:draft.date,roomId:draft.roomId,stake:draft.stake,hours:Number(draft.hours||0),hands:Number(draft.hands||0),tableResult:Number(draft.tableResult||0),rake:Number(draft.rake||0),lbPoints:Number(draft.lbPoints||0),lbRank:draft.lbRank,lbReward:Number(draft.lbReward||0),rakeback:Number(draft.rakeback||0),bonuses:Number(draft.bonuses||0),notes:draft.notes},result=session.tableResult+session.lbReward+session.rakeback+session.bonuses;setState((current)=>current&&({...current,cashSessions:[...current.cashSessions,session],rooms:current.rooms.map((room)=>room.id===session.roomId?{...room,currentBalance:room.currentBalance+result}:room),drafts:{...current.drafts,cash:cashDraft(rooms[0]?.id||"")}}));};
  return <div className="stack"><section className="entry-intro"><div><p className="eyebrow">CASH SESSION</p><h2>Log the numbers that matter.</h2><p>Core fields stay short. Optional reward details unlock the full analysis. Your draft stays saved while you check another tab.</p></div></section><section className="panel"><form className="entry" onSubmit={save}><div className="form-grid"><label>Date<input type="date" value={draft.date} onChange={(event)=>change("date",event.target.value)} required/></label><label>Room<select value={draft.roomId} onChange={(event)=>change("roomId",event.target.value)}>{rooms.map((room)=><option key={room.id} value={room.id}>{room.name} · {room.currency}</option>)}</select></label><label>Stake<select value={draft.stake} onChange={(event)=>change("stake",event.target.value)}>{["NL10","NL25","NL50","NL100","NL200","PLO25","PLO50","PLO100"].map((stake)=><option key={stake}>{stake}</option>)}</select></label><label>Hours<input type="number" step=".1" value={draft.hours} onChange={(event)=>change("hours",event.target.value)} required/></label><label>Hands<input type="number" value={draft.hands} onChange={(event)=>change("hands",event.target.value)} required/></label><label>Table result<input type="number" step=".01" value={draft.tableResult} onChange={(event)=>change("tableResult",event.target.value)} required/></label></div><details><summary>Rake, leaderboard & rewards <span>Optional</span></summary><div className="form-grid details"><label>Rake paid<input type="number" step=".01" value={draft.rake} onChange={(event)=>change("rake",event.target.value)}/></label><label>LB points<input type="number" value={draft.lbPoints} onChange={(event)=>change("lbPoints",event.target.value)}/></label><label>Final LB rank<input placeholder="#" value={draft.lbRank} onChange={(event)=>change("lbRank",event.target.value)}/></label><label>LB reward<input type="number" step=".01" value={draft.lbReward} onChange={(event)=>change("lbReward",event.target.value)}/></label><label>Rakeback<input type="number" step=".01" value={draft.rakeback} onChange={(event)=>change("rakeback",event.target.value)}/></label><label>Other bonuses<input type="number" step=".01" value={draft.bonuses} onChange={(event)=>change("bonuses",event.target.value)}/></label></div></details><label>Notes<textarea rows={2} placeholder="Mental game, pool notes, review tags…" value={draft.notes} onChange={(event)=>change("notes",event.target.value)}/></label><footer className="end"><button className="primary">Save cash session</button></footer></form></section><History state={state} setState={setState} mode="cash"/></div>;
}

function History({ state, setState, mode }: { state: AppState; setState: Setter; mode: Mode }) {
  const [openDay,setOpenDay]=useState<string|null>(null);
  if(mode==="tournament"){const days=[...state.tournamentDays].sort((a,b)=>b.date.localeCompare(a.date));return <section className="panel"><header><div><p className="eyebrow">HISTORY</p><h2>Daily results</h2></div></header>{days.length?<div className="history-list">{days.map((day)=>{const result=day.entries.reduce((sum,entry)=>sum+entry.cashes-entry.buyIns,0),open=openDay===day.id;return <article className="history-day" key={day.id}><div className="row history-summary"><time>{day.date}</time><b>{day.entries.map((entry)=>roomName(state.rooms,entry.roomId)).join(", ")}</b><span>{day.entries.reduce((sum,entry)=>sum+entry.tournaments,0)} MTTs · {day.duration}h</span><strong className={result>=0?"pos":"neg"}>{signed(result)}</strong><button className="secondary details-button" aria-expanded={open} onClick={()=>setOpenDay(open?null:day.id)}>{open?"Hide":"Details"}</button></div>{open&&<div className="history-details"><header><span>Room</span><span>MTTs</span><span>Buy-ins</span><span>Cashes</span><span>Profit / loss</span></header>{day.entries.map((entry)=><div key={entry.roomId}><b>{roomName(state.rooms,entry.roomId)}</b><span>{entry.tournaments}</span><span>{money(entry.buyIns,roomCurrency(state.rooms,entry.roomId))}</span><span>{money(entry.cashes,roomCurrency(state.rooms,entry.roomId))}</span><strong className={entry.cashes-entry.buyIns>=0?"pos":"neg"}>{signed(entry.cashes-entry.buyIns,roomCurrency(state.rooms,entry.roomId))}</strong></div>)}{day.notes&&<p><b>Notes:</b> {day.notes}</p>}<button className="danger-link" onClick={()=>setState((current)=>{if(!current)return current;const results=new Map<string,number>();day.entries.forEach((entry)=>results.set(entry.roomId,(results.get(entry.roomId)||0)+entry.cashes-entry.buyIns));return {...current,tournamentDays:current.tournamentDays.filter((item)=>item.id!==day.id),rooms:current.rooms.map((room)=>({...room,currentBalance:room.currentBalance-(results.get(room.id)||0)}))}})}>Delete this daily result</button></div>}</article>})}</div>:<Empty>Your tournament days will appear here.</Empty>}</section>}
  const sessions=[...state.cashSessions].sort((a,b)=>b.date.localeCompare(a.date));return <section className="panel"><header><div><p className="eyebrow">HISTORY</p><h2>Cash sessions</h2></div></header>{sessions.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Room</th><th>Stake</th><th>Hours</th><th>Hands</th><th>Result</th><th>bb/100</th><th>$/hour</th><th>Rake bb/100</th><th>Actual RB</th><th/></tr></thead><tbody>{sessions.map((session)=>{const rewards=session.lbReward+session.rakeback+session.bonuses,total=session.tableResult+rewards,bb=bigBlind(session.stake);return <tr key={session.id}><td>{session.date}</td><td>{roomName(state.rooms,session.roomId)}</td><td>{session.stake}</td><td>{session.hours.toFixed(1)}</td><td>{session.hands.toLocaleString()}</td><td className={total>=0?"pos":"neg"}>{signed(total,roomCurrency(state.rooms,session.roomId))}</td><td>{session.hands&&bb?(session.tableResult/bb/session.hands*100).toFixed(2):"—"}</td><td>{session.hours?money(total/session.hours,roomCurrency(state.rooms,session.roomId)):"—"}</td><td>{session.hands&&bb?(session.rake/bb/session.hands*100).toFixed(2):"—"}</td><td>{session.rake?percent(rewards/session.rake*100):"—"}</td><td><button className="remove" onClick={()=>setState((current)=>current&&({...current,cashSessions:current.cashSessions.filter((item)=>item.id!==session.id),rooms:current.rooms.map((room)=>room.id===session.roomId?{...room,currentBalance:room.currentBalance-total}:room)}))}>×</button></td></tr>})}</tbody></table></div>:<Empty>Your cash sessions will appear here.</Empty>}</section>;
}

function Rakeback({ state, setState, mode }: { state: AppState; setState: Setter; mode: Mode }) {
  const rooms=roomFilter(state,mode),rewards=state.rewards.filter((r)=>r.mode===mode).sort((a,b)=>b.date.localeCompare(a.date)),total=(c:Currency)=>rewards.filter((r)=>roomCurrency(state.rooms,r.roomId)===c).reduce((s,r)=>s+r.amount,0);
  const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget),r:Reward={id:uid(),date:String(f.get("date")),roomId:String(f.get("roomId")),mode,amount:num(f.get("amount")),type:String(f.get("type")) as Reward["type"],comment:String(f.get("comment")||"")};setState((s)=>s&&({...s,rewards:[...s.rewards,r]}));event.currentTarget.reset();};
  return <div className="stack"><section className="bankroll"><div><span>Total USD rewards</span><b className="pos">{money(total("USD"))}</b></div><div><span>Total EUR rewards</span><b className="pos">{money(total("EUR"),"EUR")}</b></div><p>Track payments not already included in a session.</p></section><section className="panel"><header><div><p className="eyebrow">NEW REWARD</p><h2>Add rakeback or bonus</h2></div></header><form className="inline" onSubmit={save}><label>Date<input name="date" type="date" defaultValue={today}/></label><label>Room<select name="roomId">{rooms.map((r)=><option key={r.id} value={r.id}>{r.name} · {r.currency}</option>)}</select></label><label>Type<select name="type"><option value="rakeback">Rakeback</option><option value="leaderboard">Leaderboard</option><option value="bonus">Bonus</option><option value="other">Other</option></select></label><label>Amount<input name="amount" type="number" step=".01" required/></label><label className="grow">Comment<input name="comment" placeholder="Weekly payment…"/></label><button className="primary">Add</button></form></section><section className="panel"><header><div><p className="eyebrow">REWARD LOG</p><h2>Rakeback history</h2></div></header>{rewards.length?<div className="list">{rewards.map((r)=><div className="row delete-row" key={r.id}><time>{r.date}</time><b>{roomName(state.rooms,r.roomId)}</b><span>{r.type} · {r.comment||"No comment"}</span><strong className="pos">+{money(r.amount,roomCurrency(state.rooms,r.roomId))}</strong><button className="remove" onClick={()=>setState((s)=>s&&({...s,rewards:s.rewards.filter((x)=>x.id!==r.id)}))}>×</button></div>)}</div>:<Empty>No rewards logged yet.</Empty>}</section></div>;
}

function Settings({ state, setState, demo, lock, vault, importVault }: { state: AppState; setState: Setter; demo: boolean; lock:()=>void; vault?: Vault; importVault:(vault:Vault)=>void }) {
  const download=()=>{if(!vault)return;const url=URL.createObjectURL(new Blob([JSON.stringify(vault)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=`grindtrack-backup-${today}.json`;a.click();URL.revokeObjectURL(url);};
  const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const raw=await file.text(),imported=JSON.parse(raw) as Vault;if(!imported.salt||!imported.iv||!imported.cipher)throw new Error();importVault(imported);alert("Backup imported as a separate account. Select it and unlock with its PIN.");}catch{alert("Not a valid GrindTrack backup.")}};
  const used=new Set([...state.tournamentDays.flatMap((d)=>d.entries.map((e)=>e.roomId)),...state.cashSessions.map((x)=>x.roomId),...state.rewards.map((r)=>r.roomId)]);
  return <div className="stack"><section className="panel setting"><div><p className="eyebrow">PROFILE</p><h2>Your private journal</h2><p>Nothing is uploaded to GitHub or shared with other players.</p></div><label>Player name<input value={state.profileName} onChange={(e)=>setState((s)=>s&&({...s,profileName:e.target.value}))}/></label></section><section className="panel setting"><div><p className="eyebrow">BACKUP</p><h2>Protect your history</h2><p>Export an encrypted backup regularly. Imported backups become separate accounts.</p></div><aside><button className="secondary" disabled={demo||!vault} onClick={download}>Export encrypted backup</button><label className="secondary file">Import backup<input type="file" accept="application/json" disabled={demo} onChange={upload}/></label></aside></section><section className="panel"><header><div><p className="eyebrow">ROOMS</p><h2>Manage rooms</h2></div></header><div className="manage">{state.rooms.map((r)=><div key={r.id}><i>{r.name.slice(0,2).toUpperCase()}</i><b>{r.name}</b><small>{r.kind} · {r.mode} · {r.currency}</small><button className="remove" disabled={used.has(r.id)} onClick={()=>setState((s)=>s&&({...s,rooms:s.rooms.filter((x)=>x.id!==r.id)}))}>×</button></div>)}</div></section><section className="panel setting"><div><p className="eyebrow">PRIVACY</p><h2>{demo?"Leave demo":"Log out of this vault"}</h2><p>{demo?"Demo changes are temporary.":"Return to the account selector. Your encrypted data stays on this device."}</p></div><button className="secondary" onClick={lock}>{demo?"Exit demo":"Log out"}</button></section></div>;
}

export default function App() {
  const [state,setState]=useState<AppState|null>(null),[key,setKey]=useState<CryptoKey|null>(null),[salt,setSalt]=useState<Uint8Array|null>(null),[demo,setDemo]=useState(false),[mode,setMode]=useState<Mode>("tournament"),[tab,setTab]=useState<Tab>("dashboard"),[saved,setSaved]=useState(true),[vaults,setVaults]=useState<StoredVault[]>(()=>loadVaults()),[activeVaultId,setActiveVaultId]=useState<string|null>(null);
  useEffect(()=>{if(!state||!key||!salt||demo||!activeVaultId)return;setSaved(false);const timer=setTimeout(async()=>{const encrypted=await encryptState(state,key,salt);setVaults((current)=>{const next=current.map((stored)=>stored.id===activeVaultId?{...stored,name:state.profileName,vault:encrypted}:stored);saveVaults(next);return next});setSaved(true)},300);return()=>clearTimeout(timer)},[state,key,salt,demo,activeVaultId]);
  if(!state)return <Gate vaults={vaults} setVaults={setVaults} enter={(next,nextKey,nextSalt,isDemo=false,vaultId)=>{setState(next);setKey(nextKey||null);setSalt(nextSalt||null);setDemo(isDemo);setActiveVaultId(vaultId||null)}}/>;
  const nav:{id:Tab;label:string;sub:string}[]=[{id:"dashboard",label:"Dashboard",sub:"Overview"},{id:"balances",label:"Balances",sub:"Bankroll"},{id:"daily",label:mode==="tournament"?"Daily grind":"Sessions",sub:"Add result"},{id:"rakeback",label:"Rakeback",sub:"Rewards"},{id:"settings",label:"Settings",sub:"Data"}];
  const leave=()=>{setState(null);setKey(null);setSalt(null);setDemo(false);setActiveVaultId(null);setTab("dashboard")};
  const lock=async()=>{if(state&&key&&salt&&!demo&&activeVaultId){const encrypted=await encryptState(state,key,salt),next=vaults.map((stored)=>stored.id===activeVaultId?{...stored,name:state.profileName,vault:encrypted}:stored);saveVaults(next);setVaults(next)}leave()};
  const importVault=(vault:Vault)=>{const next=[...vaults,{id:uid(),name:`Imported account ${vaults.length+1}`,vault}];saveVaults(next);setVaults(next);leave()};
  const activeVault=vaults.find((stored)=>stored.id===activeVaultId)?.vault;
  return <div className="shell"><aside className="side"><div className="brand"><div className="logo small">GT</div><span><b>GrindTrack</b><small>PRIVATE JOURNAL</small></span></div><div className="mode"><button className={mode==="tournament"?"active":""} onClick={()=>setMode("tournament")}>MTT</button><button className={mode==="cash"?"active":""} onClick={()=>setMode("cash")}>CASH</button></div><nav>{nav.map((n)=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>setTab(n.id)}><i/><span>{n.label}<small>{n.sub}</small></span></button>)}</nav><footer><i className={saved?"":"saving"}/>{demo?"Demo · not saved":saved?"Encrypted · saved":"Encrypting…"}</footer></aside><main className="content"><header className="top"><div><p className="eyebrow">{mode==="tournament"?"TOURNAMENT GRIND":"CASH GRIND"}</p><h1>{nav.find((n)=>n.id===tab)?.label}</h1></div><div className="profile"><span><b>{state.profileName}</b><small>{demo?"Demo vault":"Private vault"}</small></span><i>{state.profileName.slice(0,2).toUpperCase()}</i><button className="logout" onClick={lock}>Log out</button></div></header>{tab==="dashboard"&&<Dashboard state={state} mode={mode}/>} {tab==="balances"&&<Balances state={state} setState={setState} mode={mode}/>} {tab==="daily"&&(mode==="tournament"?<TournamentDaily state={state} setState={setState}/>:<CashDaily state={state} setState={setState}/>)} {tab==="rakeback"&&<Rakeback state={state} setState={setState} mode={mode}/>} {tab==="settings"&&<Settings state={state} setState={setState} demo={demo} lock={lock} vault={activeVault} importVault={importVault}/>}</main><nav className="mobile">{nav.slice(0,4).map((n)=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>setTab(n.id)}><i/>{n.label.replace("Daily grind","Daily")}</button>)}</nav></div>;
}
