import { type ChangeEvent, type Dispatch, type FormEvent, type SetStateAction, useEffect, useMemo, useRef, useState } from "react";
import type { AppState, CashSession, Currency, Mode, Reward, Room, Tab, Vault } from "./types";
import { VAULT_KEY, bigBlind, decryptState, demoState, deriveKey, emptyState, encryptState, money, num, percent, roomCurrency, roomName, signed, today, uid } from "./data";

type Setter = Dispatch<SetStateAction<AppState | null>>;
const roomFilter = (state: AppState, mode: Mode) => state.rooms.filter((r) => r.kind === "room" && (r.mode === mode || r.mode === "both"));

function Metric({ label, value, note, tone = "" }: { label: string; value: string; note: string; tone?: string }) {
  return <article className="metric"><span>{label}</span><strong className={tone}>{value}</strong><small>{note}</small></article>;
}
function Empty({ children }: { children: string }) { return <div className="empty"><b>—</b><span>{children}</span></div>; }

function ProfitChart({ points }: { points: { date: string; value: number }[] }) {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = ref.current; if (!canvas) return;
    const draw = () => {
      const box = canvas.getBoundingClientRect(), dpr = window.devicePixelRatio || 1;
      canvas.width = box.width * dpr; canvas.height = box.height * dpr;
      const c = canvas.getContext("2d"); if (!c) return; c.scale(dpr, dpr); c.clearRect(0, 0, box.width, box.height);
      if (!points.length) return; const values = points.map((p) => p.value), min = Math.min(0, ...values), max = Math.max(1, ...values), span = max - min || 1;
      const x = (i: number) => 18 + i / Math.max(1, points.length - 1) * (box.width - 36), y = (v: number) => 18 + (max - v) / span * (box.height - 46);
      c.strokeStyle = "#303030"; c.beginPath(); c.moveTo(18, y(0)); c.lineTo(box.width - 18, y(0)); c.stroke();
      const g = c.createLinearGradient(0, 18, 0, box.height - 28); g.addColorStop(0, "rgba(126,231,135,.24)"); g.addColorStop(1, "rgba(126,231,135,0)");
      c.beginPath(); points.forEach((p, i) => i ? c.lineTo(x(i), y(p.value)) : c.moveTo(x(i), y(p.value))); c.lineTo(x(points.length - 1), box.height - 28); c.lineTo(x(0), box.height - 28); c.closePath(); c.fillStyle = g; c.fill();
      c.beginPath(); points.forEach((p, i) => i ? c.lineTo(x(i), y(p.value)) : c.moveTo(x(i), y(p.value))); c.strokeStyle = "#7ee787"; c.lineWidth = 2.5; c.lineJoin = "round"; c.stroke();
      points.forEach((p, i) => { c.beginPath(); c.arc(x(i), y(p.value), 3, 0, Math.PI * 2); c.fillStyle = "#111"; c.fill(); c.strokeStyle = "#7ee787"; c.stroke(); });
      c.fillStyle = "#777"; c.font = "10px Inter"; c.fillText(points[0].date.slice(5), 18, box.height - 7); const end = points.at(-1)!.date.slice(5); c.fillText(end, box.width - 18 - c.measureText(end).width, box.height - 7);
    };
    draw(); const observer = new ResizeObserver(draw); observer.observe(canvas); return () => observer.disconnect();
  }, [points]);
  return <canvas ref={ref} className="chart" aria-label="Cumulative USD profit graph" />;
}

function Gate({ hasVault, enter }: { hasVault: boolean; enter: (state: AppState, key?: CryptoKey, salt?: Uint8Array, demo?: boolean) => void }) {
  const [error, setError] = useState("");
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setError(""); const form = new FormData(event.currentTarget), pin = String(form.get("pin") || "");
    try {
      if (hasVault) { const vault = JSON.parse(localStorage.getItem(VAULT_KEY) || "") as Vault; const opened = await decryptState(vault, pin); enter(opened.state, opened.key, opened.salt); }
      else { if (pin.length < 4) throw new Error("short"); const salt = crypto.getRandomValues(new Uint8Array(16)), key = await deriveKey(pin, salt), state = emptyState(String(form.get("name") || "Player").trim() || "Player"); localStorage.setItem(VAULT_KEY, JSON.stringify(await encryptState(state, key, salt))); enter(state, key, salt); }
    } catch (reason) { setError(reason instanceof Error && reason.message === "short" ? "Use at least 4 characters for your PIN." : "That PIN does not unlock this vault."); }
  };
  return <main className="gate"><section><div className="logo">GT</div><p className="eyebrow">ONLINE POKER JOURNAL</p><h1>Own your grind.</h1><p className="lead">Cash and tournament performance without the spreadsheet. Your records are encrypted and stay on this device.</p>
    <form onSubmit={submit}>{!hasVault && <label>Player name<input name="name" autoFocus placeholder="Your screen name" /></label>}<label>{hasVault ? "Private PIN" : "Create private PIN"}<input name="pin" type="password" autoFocus={hasVault} placeholder={hasVault ? "Enter your PIN" : "4+ characters"} /></label>{error && <p className="error">{error}</p>}<button className="primary">{hasVault ? "Unlock GrindTrack" : "Create private vault"}</button></form>
    <button className="link" onClick={() => enter(demoState(), undefined, undefined, true)}>Explore with demo data →</button><div className="privacy"><i>●</i><span><b>Device-only by design</b><small>Friends use the same link, but get a separate vault in their own browser.</small></span></div>
  </section></main>;
}

function Dashboard({ state, mode }: { state: AppState; mode: Mode }) {
  const stats = useMemo(() => {
    if (mode === "tournament") {
      const entries = state.tournamentDays.flatMap((d) => d.entries).filter((e) => roomCurrency(state.rooms, e.roomId) === "USD");
      const buy = entries.reduce((s, e) => s + e.buyIns, 0), cash = entries.reduce((s, e) => s + e.cashes, 0), volume = entries.reduce((s, e) => s + e.tournaments, 0);
      const rewards = state.rewards.filter((r) => r.mode === mode && roomCurrency(state.rooms, r.roomId) === "USD").reduce((s, r) => s + r.amount, 0);
      return { pure: cash - buy, rewards, total: cash - buy + rewards, volume, hours: state.tournamentDays.reduce((s, d) => s + d.duration, 0), one: volume ? buy / volume : 0, two: buy ? (cash - buy) / buy * 100 : 0, rake: 0 };
    }
    const sessions = state.cashSessions.filter((s) => roomCurrency(state.rooms, s.roomId) === "USD");
    const pure = sessions.reduce((s, x) => s + x.tableResult, 0), builtIn = sessions.reduce((s, x) => s + x.lbReward + x.rakeback + x.bonuses, 0), external = state.rewards.filter((r) => r.mode === mode && roomCurrency(state.rooms, r.roomId) === "USD").reduce((s, r) => s + r.amount, 0);
    const volume = sessions.reduce((s, x) => s + x.hands, 0), hours = sessions.reduce((s, x) => s + x.hours, 0), rake = sessions.reduce((s, x) => s + x.rake, 0), bbWon = sessions.reduce((s, x) => s + x.tableResult / (bigBlind(x.stake) || 1), 0);
    return { pure, rewards: builtIn + external, total: pure + builtIn + external, volume, hours, one: hours ? (pure + builtIn + external) / hours : 0, two: volume ? bbWon / volume * 100 : 0, rake };
  }, [state, mode]);
  const points = useMemo(() => { const days = new Map<string, number>(); if (mode === "tournament") state.tournamentDays.forEach((d) => d.entries.forEach((e) => roomCurrency(state.rooms, e.roomId) === "USD" && days.set(d.date, (days.get(d.date) || 0) + e.cashes - e.buyIns))); else state.cashSessions.forEach((s) => roomCurrency(state.rooms, s.roomId) === "USD" && days.set(s.date, (days.get(s.date) || 0) + s.tableResult + s.lbReward + s.rakeback + s.bonuses)); state.rewards.filter((r) => r.mode === mode && roomCurrency(state.rooms, r.roomId) === "USD").forEach((r) => days.set(r.date, (days.get(r.date) || 0) + r.amount)); let running = 0; return [...days].sort(([a], [b]) => a.localeCompare(b)).map(([date, value]) => ({ date, value: running += value })); }, [state, mode]);
  const recent = mode === "tournament" ? [...state.tournamentDays].sort((a,b) => b.date.localeCompare(a.date)).slice(0,5).map((d) => ({ id:d.id,date:d.date,name:`${d.entries.length} rooms`,detail:`${d.entries.reduce((s,e)=>s+e.tournaments,0)} MTTs`,result:d.entries.reduce((s,e)=>s+e.cashes-e.buyIns,0),currency:"USD" as Currency })) : [...state.cashSessions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map((s)=>({id:s.id,date:s.date,name:roomName(state.rooms,s.roomId),detail:`${s.stake} · ${s.hands.toLocaleString()} hands`,result:s.tableResult+s.lbReward+s.rakeback+s.bonuses,currency:roomCurrency(state.rooms,s.roomId)}));
  return <div className="stack"><section className="hero"><div><p className="eyebrow">OVERALL RESULT · USD</p><strong className={stats.total >= 0 ? "pos" : "neg"}>{signed(stats.total)}</strong><small>{stats.volume.toLocaleString()} {mode === "tournament" ? "tournaments" : "hands"} · {stats.hours.toFixed(1)} hours</small></div><aside><span>Pure profit<b>{signed(stats.pure)}</b></span><span>RB + bonuses<b>{signed(stats.rewards)}</b></span></aside></section>
    <section className="metrics">{mode === "tournament" ? <><Metric label="ABI" value={money(stats.one)} note="Average buy-in"/><Metric label="ROI" value={percent(stats.two)} note="Before rakeback" tone={stats.two >= 0 ? "pos" : "neg"}/><Metric label="$/MTT" value={money(stats.volume ? stats.pure / stats.volume : 0)} note="Pure profit per entry"/><Metric label="Rewards share" value={percent(stats.total ? stats.rewards / Math.abs(stats.total) * 100 : 0)} note="Of overall result"/></> : <><Metric label="Win rate" value={`${stats.two.toFixed(2)} bb/100`} note="Table result only" tone={stats.two >= 0 ? "pos" : "neg"}/><Metric label="$/hour" value={money(stats.one)} note="Including rewards" tone={stats.one >= 0 ? "pos" : "neg"}/><Metric label="Total rake" value={money(stats.rake)} note="Tracked sessions"/><Metric label="Actual RB" value={percent(stats.rake ? stats.rewards / stats.rake * 100 : 0)} note="Rewards ÷ rake"/></>}</section>
    <section className="panel"><header><div><p className="eyebrow">PERFORMANCE</p><h2>Overall graph</h2></div><small className="legend"><i/> Cumulative USD</small></header>{points.length ? <ProfitChart points={points}/> : <Empty>Add your first result to draw the graph.</Empty>}</section>
    <section className="panel"><header><div><p className="eyebrow">LATEST</p><h2>Recent grind</h2></div></header>{recent.length ? <div className="list">{recent.map((x)=><div className="row" key={x.id}><time>{x.date}</time><b>{x.name}</b><span>{x.detail}</span><strong className={x.result>=0?"pos":"neg"}>{signed(x.result,x.currency)}</strong></div>)}</div>:<Empty>No sessions yet. Your latest results will appear here.</Empty>}</section>
  </div>;
}

function Balances({ state, setState, mode }: { state: AppState; setState: Setter; mode: Mode }) {
  const rooms = state.rooms.filter((r) => r.mode === mode || r.mode === "both" || r.kind === "wallet");
  const resultToday = (id:string) => mode === "tournament" ? state.tournamentDays.filter((d)=>d.date===today).flatMap((d)=>d.entries).filter((e)=>e.roomId===id).reduce((s,e)=>s+e.cashes-e.buyIns,0) : state.cashSessions.filter((x)=>x.date===today&&x.roomId===id).reduce((s,x)=>s+x.tableResult+x.lbReward+x.rakeback+x.bonuses,0);
  const add = (event:FormEvent<HTMLFormElement>) => { event.preventDefault(); const f=new FormData(event.currentTarget), balance=num(f.get("balance")); setState((s)=>s&&({...s,rooms:[...s.rooms,{id:uid(),name:String(f.get("name")),kind:String(f.get("kind")) as Room["kind"],mode:String(f.get("mode")) as Room["mode"],currency:String(f.get("currency")) as Currency,startingBalance:balance,currentBalance:balance}]})); event.currentTarget.reset(); };
  return <div className="stack"><section className="bankroll"><div><span>USD bankroll</span><b>{money(rooms.filter((r)=>r.currency==="USD").reduce((s,r)=>s+r.currentBalance,0))}</b></div><div><span>EUR bankroll</span><b>{money(rooms.filter((r)=>r.currency==="EUR").reduce((s,r)=>s+r.currentBalance,0),"EUR")}</b></div><p>Reconcile balances manually. Today’s result comes from tracked play.</p></section><section className="room-grid">{rooms.map((r)=><article className="room" key={r.id}><header><i>{r.name.slice(0,2).toUpperCase()}</i><span><b>{r.name}</b><small>{r.kind} · {r.currency}</small></span><strong className={resultToday(r.id)>=0?"pos":"neg"}>{signed(resultToday(r.id),r.currency)}</strong></header><label>Current balance<div className="money-field"><i>{r.currency==="USD"?"$":"€"}</i><input type="number" step=".01" value={r.currentBalance} onChange={(e)=>setState((s)=>s&&({...s,rooms:s.rooms.map((x)=>x.id===r.id?{...x,currentBalance:Number(e.target.value)}:x)}))}/></div></label><footer><span>Starting<b>{money(r.startingBalance,r.currency)}</b></span><span>Change<b className={r.currentBalance-r.startingBalance>=0?"pos":"neg"}>{signed(r.currentBalance-r.startingBalance,r.currency)}</b></span></footer></article>)}</section><section className="panel"><header><div><p className="eyebrow">BANKROLL</p><h2>Add room or wallet</h2></div></header><form className="inline" onSubmit={add}><label>Name<input name="name" required placeholder="e.g. Nike"/></label><label>Type<select name="kind"><option value="room">Poker room</option><option value="wallet">Wallet</option></select></label><label>Used for<select name="mode" defaultValue={mode}><option value="tournament">MTT</option><option value="cash">Cash</option><option value="both">Both</option></select></label><label>Currency<select name="currency"><option>USD</option><option>EUR</option></select></label><label>Starting balance<input name="balance" type="number" step=".01" defaultValue="0"/></label><button className="primary">Add</button></form></section></div>;
}

function TournamentDaily({ state, setState }: { state: AppState; setState: Setter }) {
  const rooms=roomFilter(state,"tournament"), [rows,setRows]=useState([{key:uid(),roomId:rooms[0]?.id||"",tournaments:0,buyIns:0,cashes:0}]);
  const change=(key:string,field:string,value:string)=>setRows((all)=>all.map((r)=>r.key===key?{...r,[field]:field==="roomId"?value:Number(value)}:r));
  const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget),entries=rows.filter((r)=>r.roomId&&(r.tournaments||r.buyIns||r.cashes)).map(({key,...r})=>r);if(!entries.length)return;setState((s)=>s&&({...s,tournamentDays:[...s.tournamentDays,{id:uid(),date:String(f.get("date")),duration:num(f.get("duration")),notes:String(f.get("notes")||""),entries}]}));setRows([{key:uid(),roomId:rooms[0]?.id||"",tournaments:0,buyIns:0,cashes:0}]);event.currentTarget.reset();};
  const total=rows.reduce((s,r)=>s+r.cashes-r.buyIns,0),count=rows.reduce((s,r)=>s+r.tournaments,0),buy=rows.reduce((s,r)=>s+r.buyIns,0);
  return <div className="stack"><section className="entry-intro"><div><p className="eyebrow">FAST DAILY ENTRY</p><h2>One row per room. Not per tournament.</h2><p>Enter totals after the session. ABI and ROI calculate themselves.</p></div><aside><span>Session result</span><b className={total>=0?"pos":"neg"}>{signed(total)}</b><small>{count} MTTs · ABI {money(count?buy/count:0)}</small></aside></section><section className="panel"><form className="entry" onSubmit={save}><div className="form-grid top"><label>Date<input name="date" type="date" defaultValue={today} required/></label><label>Duration<input name="duration" type="number" step=".1" placeholder="Hours"/></label><label>Notes<input name="notes" placeholder="Focus, mistakes, deep runs…"/></label></div><div className="entry-table"><header><span>Room</span><span>Tournaments</span><span>Total buy-ins</span><span>Total cashes</span><span>Result</span><span/></header>{rows.map((r)=><div key={r.key}><select value={r.roomId} onChange={(e)=>change(r.key,"roomId",e.target.value)}>{rooms.map((x)=><option key={x.id} value={x.id}>{x.name} · {x.currency}</option>)}</select><input aria-label="Tournaments" type="number" value={r.tournaments||""} onChange={(e)=>change(r.key,"tournaments",e.target.value)}/><input aria-label="Buy-ins" type="number" step=".01" value={r.buyIns||""} onChange={(e)=>change(r.key,"buyIns",e.target.value)}/><input aria-label="Cashes" type="number" step=".01" value={r.cashes||""} onChange={(e)=>change(r.key,"cashes",e.target.value)}/><b className={r.cashes-r.buyIns>=0?"pos":"neg"}>{signed(r.cashes-r.buyIns,roomCurrency(state.rooms,r.roomId))}</b><button type="button" className="remove" onClick={()=>setRows((all)=>all.filter((x)=>x.key!==r.key))}>×</button></div>)}</div><footer><button type="button" className="secondary" onClick={()=>setRows((all)=>[...all,{key:uid(),roomId:rooms[0]?.id||"",tournaments:0,buyIns:0,cashes:0}])}>+ Add room</button><button className="primary">Save daily result</button></footer></form></section><History state={state} setState={setState} mode="tournament"/></div>;
}

function CashDaily({ state, setState }: { state: AppState; setState: Setter }) {
  const rooms=roomFilter(state,"cash");
  const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget),x:CashSession={id:uid(),date:String(f.get("date")),roomId:String(f.get("roomId")),stake:String(f.get("stake")),hours:num(f.get("hours")),hands:num(f.get("hands")),tableResult:num(f.get("tableResult")),rake:num(f.get("rake")),lbPoints:num(f.get("lbPoints")),lbRank:String(f.get("lbRank")||""),lbReward:num(f.get("lbReward")),rakeback:num(f.get("rakeback")),bonuses:num(f.get("bonuses")),notes:String(f.get("notes")||"")};setState((s)=>s&&({...s,cashSessions:[...s.cashSessions,x]}));event.currentTarget.reset();};
  return <div className="stack"><section className="entry-intro"><div><p className="eyebrow">CASH SESSION</p><h2>Log the numbers that matter.</h2><p>Core fields stay short. Optional reward details unlock the full analysis.</p></div></section><section className="panel"><form className="entry" onSubmit={save}><div className="form-grid"><label>Date<input name="date" type="date" defaultValue={today} required/></label><label>Room<select name="roomId">{rooms.map((r)=><option key={r.id} value={r.id}>{r.name} · {r.currency}</option>)}</select></label><label>Stake<select name="stake" defaultValue="NL25">{["NL10","NL25","NL50","NL100","NL200","PLO25","PLO50","PLO100"].map((x)=><option key={x}>{x}</option>)}</select></label><label>Hours<input name="hours" type="number" step=".1" required/></label><label>Hands<input name="hands" type="number" required/></label><label>Table result<input name="tableResult" type="number" step=".01" required/></label></div><details><summary>Rake, leaderboard & rewards <span>Optional</span></summary><div className="form-grid details"><label>Rake paid<input name="rake" type="number" step=".01"/></label><label>LB points<input name="lbPoints" type="number"/></label><label>Final LB rank<input name="lbRank" placeholder="#"/></label><label>LB reward<input name="lbReward" type="number" step=".01"/></label><label>Rakeback<input name="rakeback" type="number" step=".01"/></label><label>Other bonuses<input name="bonuses" type="number" step=".01"/></label></div></details><label>Notes<textarea name="notes" rows={2} placeholder="Mental game, pool notes, review tags…"/></label><footer className="end"><button className="primary">Save cash session</button></footer></form></section><History state={state} setState={setState} mode="cash"/></div>;
}

function History({ state, setState, mode }: { state: AppState; setState: Setter; mode: Mode }) {
  if(mode==="tournament"){const days=[...state.tournamentDays].sort((a,b)=>b.date.localeCompare(a.date));return <section className="panel"><header><div><p className="eyebrow">HISTORY</p><h2>Daily results</h2></div></header>{days.length?<div className="list">{days.map((d)=>{const result=d.entries.reduce((s,e)=>s+e.cashes-e.buyIns,0);return <div className="row delete-row" key={d.id}><time>{d.date}</time><b>{d.entries.map((e)=>roomName(state.rooms,e.roomId)).join(", ")}</b><span>{d.entries.reduce((s,e)=>s+e.tournaments,0)} MTTs · {d.duration}h</span><strong className={result>=0?"pos":"neg"}>{signed(result)}</strong><button className="remove" onClick={()=>setState((s)=>s&&({...s,tournamentDays:s.tournamentDays.filter((x)=>x.id!==d.id)}))}>×</button></div>})}</div>:<Empty>Your tournament days will appear here.</Empty>}</section>}
  const sessions=[...state.cashSessions].sort((a,b)=>b.date.localeCompare(a.date));return <section className="panel"><header><div><p className="eyebrow">HISTORY</p><h2>Cash sessions</h2></div></header>{sessions.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Room</th><th>Stake</th><th>Hours</th><th>Hands</th><th>Result</th><th>bb/100</th><th>$/hour</th><th>Rake bb/100</th><th>Actual RB</th><th/></tr></thead><tbody>{sessions.map((x)=>{const rewards=x.lbReward+x.rakeback+x.bonuses,total=x.tableResult+rewards,bb=bigBlind(x.stake);return <tr key={x.id}><td>{x.date}</td><td>{roomName(state.rooms,x.roomId)}</td><td>{x.stake}</td><td>{x.hours.toFixed(1)}</td><td>{x.hands.toLocaleString()}</td><td className={total>=0?"pos":"neg"}>{signed(total,roomCurrency(state.rooms,x.roomId))}</td><td>{x.hands&&bb?(x.tableResult/bb/x.hands*100).toFixed(2):"—"}</td><td>{x.hours?money(total/x.hours,roomCurrency(state.rooms,x.roomId)):"—"}</td><td>{x.hands&&bb?(x.rake/bb/x.hands*100).toFixed(2):"—"}</td><td>{x.rake?percent(rewards/x.rake*100):"—"}</td><td><button className="remove" onClick={()=>setState((s)=>s&&({...s,cashSessions:s.cashSessions.filter((y)=>y.id!==x.id)}))}>×</button></td></tr>})}</tbody></table></div>:<Empty>Your cash sessions will appear here.</Empty>}</section>;
}

function Rakeback({ state, setState, mode }: { state: AppState; setState: Setter; mode: Mode }) {
  const rooms=roomFilter(state,mode),rewards=state.rewards.filter((r)=>r.mode===mode).sort((a,b)=>b.date.localeCompare(a.date)),total=(c:Currency)=>rewards.filter((r)=>roomCurrency(state.rooms,r.roomId)===c).reduce((s,r)=>s+r.amount,0);
  const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget),r:Reward={id:uid(),date:String(f.get("date")),roomId:String(f.get("roomId")),mode,amount:num(f.get("amount")),type:String(f.get("type")) as Reward["type"],comment:String(f.get("comment")||"")};setState((s)=>s&&({...s,rewards:[...s.rewards,r]}));event.currentTarget.reset();};
  return <div className="stack"><section className="bankroll"><div><span>Total USD rewards</span><b className="pos">{money(total("USD"))}</b></div><div><span>Total EUR rewards</span><b className="pos">{money(total("EUR"),"EUR")}</b></div><p>Track payments not already included in a session.</p></section><section className="panel"><header><div><p className="eyebrow">NEW REWARD</p><h2>Add rakeback or bonus</h2></div></header><form className="inline" onSubmit={save}><label>Date<input name="date" type="date" defaultValue={today}/></label><label>Room<select name="roomId">{rooms.map((r)=><option key={r.id} value={r.id}>{r.name} · {r.currency}</option>)}</select></label><label>Type<select name="type"><option value="rakeback">Rakeback</option><option value="leaderboard">Leaderboard</option><option value="bonus">Bonus</option><option value="other">Other</option></select></label><label>Amount<input name="amount" type="number" step=".01" required/></label><label className="grow">Comment<input name="comment" placeholder="Weekly payment…"/></label><button className="primary">Add</button></form></section><section className="panel"><header><div><p className="eyebrow">REWARD LOG</p><h2>Rakeback history</h2></div></header>{rewards.length?<div className="list">{rewards.map((r)=><div className="row delete-row" key={r.id}><time>{r.date}</time><b>{roomName(state.rooms,r.roomId)}</b><span>{r.type} · {r.comment||"No comment"}</span><strong className="pos">+{money(r.amount,roomCurrency(state.rooms,r.roomId))}</strong><button className="remove" onClick={()=>setState((s)=>s&&({...s,rewards:s.rewards.filter((x)=>x.id!==r.id)}))}>×</button></div>)}</div>:<Empty>No rewards logged yet.</Empty>}</section></div>;
}

function Settings({ state, setState, demo, lock }: { state: AppState; setState: Setter; demo: boolean; lock:()=>void }) {
  const download=()=>{const raw=localStorage.getItem(VAULT_KEY);if(!raw)return;const url=URL.createObjectURL(new Blob([raw],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=`grindtrack-backup-${today}.json`;a.click();URL.revokeObjectURL(url);};
  const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const raw=await file.text(),v=JSON.parse(raw) as Vault;if(!v.salt||!v.iv||!v.cipher)throw new Error();localStorage.setItem(VAULT_KEY,raw);alert("Backup imported. Lock and unlock with its PIN.");}catch{alert("Not a valid GrindTrack backup.")}};
  const used=new Set([...state.tournamentDays.flatMap((d)=>d.entries.map((e)=>e.roomId)),...state.cashSessions.map((x)=>x.roomId),...state.rewards.map((r)=>r.roomId)]);
  return <div className="stack"><section className="panel setting"><div><p className="eyebrow">PROFILE</p><h2>Your private journal</h2><p>Nothing is uploaded to GitHub or shared with other players.</p></div><label>Player name<input value={state.profileName} onChange={(e)=>setState((s)=>s&&({...s,profileName:e.target.value}))}/></label></section><section className="panel setting"><div><p className="eyebrow">BACKUP</p><h2>Protect your history</h2><p>Export an encrypted backup regularly. The same PIN is required after import.</p></div><aside><button className="secondary" disabled={demo} onClick={download}>Export encrypted backup</button><label className="secondary file">Import backup<input type="file" accept="application/json" disabled={demo} onChange={upload}/></label></aside></section><section className="panel"><header><div><p className="eyebrow">ROOMS</p><h2>Manage rooms</h2></div></header><div className="manage">{state.rooms.map((r)=><div key={r.id}><i>{r.name.slice(0,2).toUpperCase()}</i><b>{r.name}</b><small>{r.kind} · {r.mode} · {r.currency}</small><button className="remove" disabled={used.has(r.id)} onClick={()=>setState((s)=>s&&({...s,rooms:s.rooms.filter((x)=>x.id!==r.id)}))}>×</button></div>)}</div></section><section className="panel setting"><div><p className="eyebrow">PRIVACY</p><h2>{demo?"Leave demo":"Lock this vault"}</h2><p>{demo?"Demo changes are temporary.":"Encrypted data stays on this device."}</p></div><button className="secondary" onClick={lock}>{demo?"Exit demo":"Lock now"}</button></section></div>;
}

export default function App() {
  const [state,setState]=useState<AppState|null>(null),[key,setKey]=useState<CryptoKey|null>(null),[salt,setSalt]=useState<Uint8Array|null>(null),[demo,setDemo]=useState(false),[mode,setMode]=useState<Mode>("tournament"),[tab,setTab]=useState<Tab>("dashboard"),[saved,setSaved]=useState(true);
  useEffect(()=>{if(!state||!key||!salt||demo)return;setSaved(false);const timer=setTimeout(async()=>{localStorage.setItem(VAULT_KEY,JSON.stringify(await encryptState(state,key,salt)));setSaved(true)},300);return()=>clearTimeout(timer)},[state,key,salt,demo]);
  if(!state)return <Gate hasVault={Boolean(localStorage.getItem(VAULT_KEY))} enter={(s,k,sa,d=false)=>{setState(s);setKey(k||null);setSalt(sa||null);setDemo(d)}}/>;
  const nav:{id:Tab;label:string;sub:string}[]=[{id:"dashboard",label:"Dashboard",sub:"Overview"},{id:"balances",label:"Balances",sub:"Bankroll"},{id:"daily",label:mode==="tournament"?"Daily grind":"Sessions",sub:"Add result"},{id:"rakeback",label:"Rakeback",sub:"Rewards"},{id:"settings",label:"Settings",sub:"Data"}];
  const lock=()=>{setState(null);setKey(null);setSalt(null);setDemo(false)};
  return <div className="shell"><aside className="side"><div className="brand"><div className="logo small">GT</div><span><b>GrindTrack</b><small>PRIVATE JOURNAL</small></span></div><div className="mode"><button className={mode==="tournament"?"active":""} onClick={()=>setMode("tournament")}>MTT</button><button className={mode==="cash"?"active":""} onClick={()=>setMode("cash")}>CASH</button></div><nav>{nav.map((n)=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>setTab(n.id)}><i/><span>{n.label}<small>{n.sub}</small></span></button>)}</nav><footer><i className={saved?"":"saving"}/>{demo?"Demo · not saved":saved?"Encrypted · saved":"Encrypting…"}</footer></aside><main className="content"><header className="top"><div><p className="eyebrow">{mode==="tournament"?"TOURNAMENT GRIND":"CASH GRIND"}</p><h1>{nav.find((n)=>n.id===tab)?.label}</h1></div><div className="profile"><span><b>{state.profileName}</b><small>{demo?"Demo vault":"Private vault"}</small></span><i>{state.profileName.slice(0,2).toUpperCase()}</i></div></header>{tab==="dashboard"&&<Dashboard state={state} mode={mode}/>} {tab==="balances"&&<Balances state={state} setState={setState} mode={mode}/>} {tab==="daily"&&(mode==="tournament"?<TournamentDaily state={state} setState={setState}/>:<CashDaily state={state} setState={setState}/>)} {tab==="rakeback"&&<Rakeback state={state} setState={setState} mode={mode}/>} {tab==="settings"&&<Settings state={state} setState={setState} demo={demo} lock={lock}/>}</main><nav className="mobile">{nav.slice(0,4).map((n)=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>setTab(n.id)}><i/>{n.label.replace("Daily grind","Daily")}</button>)}</nav></div>;
}
